export const URGENCY_KEYWORDS: string[] = [
  "immediate action required",
  "account suspended",
  "account will be suspended",
  "account has been locked",
  "verify your account immediately",
  "your account will be closed",
  "act now",
  "within 24 hours",
  "expires today",
  "final notice",
  "unauthorized access detected",
  "suspicious activity detected",
  "your account is at risk",
  "failure to comply",
  "legal action will be taken",
  "as per rbi guidelines",
  "as per company policy",
  "confirm your identity",
  "update your kyc",
  "verify your details to avoid",
  "reply with your credentials",
  "share your login details",
  "download the attached document immediately",
  "this is time-sensitive",
];
